// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
(function(m,u,ba,S,G,E){function K(b){if(b){var d=b.url;0!=string_indexOf.call(d,"https://www.mycinema.pro/")&&0!=string_indexOf.call(d,ca)&&(u.location.href="about:blank");a=b.opt}(b=v)||(b=u.body,b=attachShadowProto&&53<T?attachShadowProto.call(b,{mode:"closed"}):b);v=b;b=createDocumentFragment.call(u);d=k("ul");d.id="opt";x&&(d.className="localPage",u.body.classList.remove("shadow"));appendChild.call(b,d);var f=v,g=k("link");g.rel="stylesheet";g.type="text/css";g.href="css/dF.css";appendChild.call(f,
g);f=createDocumentFragment.call(u);g=createTextNode.call(u,"YouTube constantly make changes, and we constantly need to make sure we are in sync.");appendChild.call(f,g);g=k("br");appendChild.call(f,g);g=createTextNode.call(u,"Last years we have been working hard to provide you with the best possible features. ");appendChild.call(f,g);g=k("br");appendChild.call(f,g);g=createTextNode.call(u,"Please don't forget to … ");appendChild.call(f,g);g=k("span");g.textContent="Support Magic Actions Development";
g.className="Il1w";g.title="Securely via PayPal to our email address \n  webmaster@mixesoft.com \n You don't need to create a PayPal account.";appendChild.call(f,g);g=k("ul"==d.localName?"li":"div");g.className="msg";appendChild.call(g,f);appendChild.call(d,g);g.style.backgroundImage="none";addEventListener.call(g,"click",da,!1);l(d,"mwvc",e("o8"),a.mwvc,0,0,x?0:{id:7,p:305,f:0});l(d,"mwvcm",e("o82"),a.mwvcm,1,!a.mwvc);l(d,"mwvct",e("o83"),a.mwvct,1,!a.mwvc);l(d,"mwvcr",e("o41"),a.mwvcr,1,!a.mwvc);
f="red LightPink orange lime GreenYellow yellow gold DodgerBlue aqua magenta DeepPink white".split(" ");g=k("li");var c=k("label");g.className="sub";setAttribute.call(g,"disabled",!a.mwvc);g.id="color";c.textContent=e("o9");appendChild.call(g,c);for(var t=0,p=f.length;t<p;t++){var h=f[t];c=k("button");c.id=h;c.style.backgroundColor=h;a.color==h&&(c.className="sel");appendChild.call(g,c);addEventListener.call(c,"click",fa,!1)}appendChild.call(d,g);f=k("li");g=k("label");f.id="mwvci";f.className="sub";
setAttribute.call(f,"disabled",!a.mwvci);g.textContent=e("o23");appendChild.call(f,g);r(f,"vc0",e("o85"),0==a.mwvci,H);r(f,"vc1",e("o24"),1==a.mwvci,H);r(f,"vc2",e("o25"),2==a.mwvci,H);r(f,"vc3",e("o26"),3==a.mwvci,H);appendChild.call(d,f);f=e("o27");g=a.gap;c=!a.mwvc;h=k("li");t=k("label");p=k("input");t.textContent=f;setAttribute.call(t,"for","gap");p.type="range";p.min=1;p.max=25;p.step=1;p.value=g;p.id="gap";p.title="Range: 1-25";appendChild.call(h,t);appendChild.call(h,p);t=k("span");t.textContent=
g;appendChild.call(h,t);h.className="sub";setAttribute.call(h,"disabled",c);appendChild.call(d,h);addEventListener.call(p,"change",ha,!1);l(d,"hq",e("o90"),a.hq,0,0,x?0:{id:7,p:306,f:0});f=k("li");f.id="hqi";f.className="sub";setAttribute.call(f,"disabled",!a.hq);r(f,"highres",e("o91"),"highres"==a.hqi,w);r(f,"hd2880",e("o92"),"hd2880"==a.hqi,w);r(f,"hd2160",e("o93"),"hd2160"==a.hqi,w);r(f,"hd1440",e("o94"),"hd1440"==a.hqi,w);r(f,"hd1080",e("o95"),"hd1080"==a.hqi,w);r(f,"hd720",e("o96"),"hd720"==
a.hqi,w);r(f,"large",e("o97"),"large"==a.hqi,w);r(f,"medium",e("o98"),"medium"==a.hqi,w);r(f,"small",e("o99"),"small"==a.hqi,w);r(f,"tiny",e("o100"),"tiny"==a.hqi,w);appendChild.call(d,f);l(d,"mrl",e("o44"),a.mrl);l(d,"wide",e("o28"),a.wide);l(d,"ww",e("o80"),a.ww);l(d,"cin",e("o29"),a.cin,0,0,x?0:{id:7,p:302,f:0});f=k("li");g=k("label");f.id="cini";f.className="sub";setAttribute.call(f,"disabled",!a.cin);g.textContent=e("o32");appendChild.call(f,g);r(f,"ca0",e("o33"),0==a.cini,L);r(f,"ca1",e("o34"),
1==a.cini,L);r(f,"ca2",e("o35"),2==a.cini,L);appendChild.call(d,f);l(d,"cina",e("o30"),a.cina,1,!a.cin);l(d,"cinf",e("o31"),a.cinf,1,!a.cin);l(d,"pause",e("o17"),a.pause);l(d,"plist",e("o19"),a.plist,1,!a.pause);l(d,"buf",e("o18"),a.buf);l(d,"buf1",e("o63"),a.buf1,1,!a.buf);l(d,"loop",e("o40"),a.loop);l(d,"c0",e("o70"),a.c0,0,0,x?0:{id:7,p:307,f:0});M(d,["c1",e("o71"),a.c1,"c4",e("o86"),a.c4],!a.c0);l(d,"anns",e("o42"),a.anns);l(d,"f0",e("o43"),a.f0);l(d,"h0",e("o50"),a.h0);M(d,["h7",e("o56"),a.h7,
"h1",e("o51"),a.h1,"h2",e("o52"),a.h2,"h3",e("o53"),a.h3,"h4",e("o54"),a.h4],!a.h0);M(d,["h5",e("o55"),a.h5,"h6",e("o64"),a.h6,"h8",e("o57"),a.h8],!a.h0);l(d,"a0",e("o60"),a.a0,0,0,x?0:{id:7,p:304,f:0});l(d,"a4",e("o81"),a.a4,1,!a.a0);l(d,"a1",e("o61"),a.a1,1,!a.a0);l(d,"a2",e("o62"),a.a2,1,!a.a0);l(d,"a3",e("o84"),a.a3,1,!a.a0);l(d,"a5",e("o20"),a.a5,1,!a.a0);f=k("li");g=k("a");f.className="opt";g.textContent="Export Options …";g.className="bttn";addEventListener.call(g,"click",ia,!1);appendChild.call(f,
g);g=k("a");g.textContent="Import Options …";g.className="bttn";addEventListener.call(g,"click",ja,!1);appendChild.call(f,g);appendChild.call(d,f);appendChild.call(v,b);y("#f0").parentElement.title="Show/Hide the Filters button so you can apply a filter (grayscale, flip, high contrast etc.) to any video";b=k("sup");b.textContent=e("m4");b.style.color="red";b.style.verticalAlign="top";appendChild.call(y("#mrl").nextElementSibling,b);y("#mrl").parentElement.title="Show/Hide the Filters button so you can apply a filter (grayscale, flip, high contrast etc.) to any video";
addEventListener.call(m,"message",ka,!1);if(N){var q=la.call(N,"sv")||null;q&&localStorage_removeItem.call(N,"sv")}x||m.top.postMessage(ma(z({t:+new Date,i:700,ver:a.ver,sv:q})),"https://www.mycinema.pro")}function ka(a){if("https://www.mycinema.pro"===(a.origin||"")&&a.data.constructor===Array)try{var d=a.data;a=[];for(var f=[3,0,0,-3],b,c=0,e=d.length;c<e;c++)b=f[c%4],c+b<e?array_push.call(a,U(d[c+b])):array_push.call(a,U(d[c]));var p=array_join.call(a,"");V(p)}catch(ea){}}function C(a,d,f){D(z({id:4,
name:a,value:d,ctx:f}))}function fa(b){y("#"+a.color).className="";a.color=this.id;this.className="sel";C("color",a.color)}function H(b){y("#vc"+a.mwvci).checked=!1;a.mwvci=F(this.id.charAt(2));this.checked=!0;C("mwvci",a.mwvci)}function L(b){y("#ca"+a.cini).checked=!1;a.cini=F(this.id.charAt(2));this.checked=!0;C("cini",a.cini)}function w(b){y("#"+a.hqi).checked=!1;a.hqi=this.id;this.checked=!0;C("hqi",a.hqi)}function W(b){b=this.id;a[b]=this.checked?!0:!1;C(b,this.checked?!0:!1,"a0"==b||"a3"==b?
!0:!1);b=this.parentElement;if("opt"==b.className)for(b=b.nextElementSibling;b&&("sub"==b.className||"sub multi"==b.className);)setAttribute.call(b,"disabled",!this.checked),b=b.nextElementSibling}function na(b){a[b.id]=F(b.value);C(b.id,F(b.value))}function ha(a){I&&(oa(I),I=null);this.nextElementSibling.textContent=this.value;I=X(na,500,this)}function r(a,d,f,c,e){var b=k("label"),g=k("input");g.type="radio";g.id=d;c&&(g.checked=!0);appendChild.call(a,g);b.textContent=f;setAttribute.call(b,"for",
d);appendChild.call(a,b);addEventListener.call(g,"click",e,!1)}function l(a,d,f,g,c,e,h){var b=k("li"),t=k("label"),p=k("input");t.textContent=f;setAttribute.call(t,"for",d);p.type="checkbox";p.id=d;p.checked=g;appendChild.call(b,p);appendChild.call(b,t);c?(b.className="sub",setAttribute.call(b,"disabled",e)):b.className="opt";h&&(d=k("span"),d.textContent="?",d.title="Learn more about this feature …",d.className="help",Object.defineProperty(d,"mafy",{value:h,writable:!1,configurable:!1,enumerable:!1}),
appendChild.call(b,d),addEventListener.call(d,"click",function(a){D(z(this.mafy))},!1));appendChild.call(a,b);addEventListener.call(p,"click",W,!1)}function M(a,d,f){for(var b=k("li"),c,e,h=0,l=d.length;h<l;h+=3)c=k("label"),e=k("input"),c.textContent=d[h+1],setAttribute.call(c,"for",d[h]),e.type="checkbox",e.id=d[h],e.checked=d[h+2],appendChild.call(b,e),appendChild.call(b,c),addEventListener.call(e,"click",W,!1);b.className="sub multi";setAttribute.call(b,"disabled",f);appendChild.call(a,b)}function da(a){D(z({id:7,
p:202,f:0}));stopPropagation.call(a)}function ia(){var b=z(a);if(Blob)var d=new Blob([b],{type:"application/json;charset=UTF-8"});else BlobBuilder&&(d=new BlobBuilder,d.append(b),d=d.getBlob("application/json;charset=UTF-8"));pa(d,"MagicActions-Options.json")}function ja(){qa(1E5,function(b){try{b=V(b)}catch(g){return}var d=a.ver,f;for(f in b)void 0!=a[f]&&(a[f]=b[f]);a.ver=d;for(D(z({id:3,opt:a}));v.firstElementChild;)removeChild.call(v,v.firstElementChild);K()})}function qa(a,d){var b=y("#openAs");
b&&removeChild.call(v,b);b=k("input");b.id="openAs";b.style.display="none";b.type="file";appendChild.call(v,b);addEventListener.call(b,"change",function(b){if((b=b.target.files)&&1==b.length&&b[0].size<a){var c=new FileReader;c.onload=function(a){d(a.target.result)};c.readAsText(b[0])}else showMsg("m12",1E3)},!1);el_click.call(b)}function pa(a,d){var b=k("a");b.href=ra(a);setAttribute.call(b,"download",d);el_click.call(b);X(function(){sa(b.href)},2E3)}function ta(a){ua("HEAD","https://www.mycinema.pro/",
0,"text",function(b){!b||200!=b.code&&304!=b.code?a():a(1)})}function ua(a,c,e,g,h){var b={code:0},d=new S;xhr_open.call(d,a,c,!0);g&&(d.responseType=g);d.onload=function(a){b.code=this.status||0;b.data=this.response;h(b)};d.onerror=function(){h(b)};d.onabort=function(){h(b)};try{xhr_send.call(d,e)}catch(ea){h(b)}}function ma(a){for(var b=[],c=[3,0,0,-3],e,h=0,k=a.length;h<k;h++)e=c[h%4],h+e<k?array_push.call(b,string_charCodeAt.call(a,h+e)):array_push.call(b,string_charCodeAt.call(a,h));return b}
function y(a){return attachShadowProto&&53<T?shadow_querySelector.call(v,a):querySelector.call(u,a)}function k(a){return createElement.call(u,a)}function c(){}var D=G.sendMessage;G=G.getURL;var e=E.getMessage;E=String.prototype;var Y=Array.prototype,B=Storage.prototype,va=Navigator.prototype,O=S.prototype,P=DocumentFragment.prototype,q=Document.prototype,Z=DOMImplementation.prototype,Q=EventTarget.prototype,J=Event.prototype,A=Node.prototype,h=Element.prototype,R=HTMLElement.prototype;HTMLMediaElement_prototype=
HTMLMediaElement.prototype;var la=B.getItem;localStorage_setItem=B.setItem;localStorage_removeItem=B.removeItem;createElement=q.createElement;addEventListener=Q.addEventListener;createDocumentFragment=q.createDocumentFragment;setAttribute=h.setAttribute;appendChild=A.appendChild;removeChild=A.removeChild;createTextNode=q.createTextNode;stopPropagation=J.stopPropagation;shadow_querySelector=P.querySelector;querySelector=q.querySelector;array_push=Y.push;array_join=Y.join;string_slice=E.slice;string_charCodeAt=
E.charCodeAt;string_indexOf=E.indexOf;el_click=R.click;xhr_open=O.open;xhr_send=O.send;attachShadowProto=h.attachShadow||void 0;B.getItem=c;B.setItem=c;B.removeItem=c;B.clear=c;va.sendBeacon=c;O.open=c;P.querySelector=c;P.querySelectorAll=c;q.createDocumentFragment=c;q.createTextNode=c;q.createElement=c;q.createElementNS=c;q.evaluate=c;q.createEvent=c;q.createCDATASection=c;q.execCommand=c;q.querySelector=c;q.querySelectorAll=c;q.write=c;q.writeln=c;Z.createHTMLDocument=c;Z.createDocument=c;Q.addEventListener=
c;Q.removeEventListener=c;J.preventDefault=c;J.stopPropagation=c;J.stopImmediatePropagation=c;A.appendChild=c;A.cloneNode=c;A.getRootNode=c;A.removeChild=c;A.replaceChild=c;A.insertBefore=c;h.attachShadow=c;h.createShadowRoot=c;h.getElementsByClassName=c;h.getElementsByTagName=c;h.getElementsByTagNameNS=c;h.append=c;h.remove=c;h.before=c;h.after=c;h.prepend=c;h.querySelector=c;h.querySelectorAll=c;h.requestPointerLock=c;h.setAttribute=c;h.removeAttribute=c;h.removeAttributeNS=c;h.removeAttributeNode=
c;h.replaceWith=c;h.insertAdjacentElement=c;h.insertAdjacentText=c;h.insertAdjacentHTML=c;R.focus=c;R.click=c;HTMLMediaElement_prototype.play=c;var z=m.JSON.stringify,V=m.JSON.parse,X=m.setTimeout,oa=m.clearTimeout,U=String.fromCharCode,F=m.parseInt,sa=m.URL.revokeObjectURL,ra=m.URL.createObjectURL,aa=ba.userAgent,T=function(){var a=string_indexOf.call(aa,"Chrome/");return-1<a?F(string_slice.call(aa,a+7)):0}(),ca=G("Mj.html"),x=m.self==m.top,v,a,I;try{var N=m.localStorage}catch(b){}addEventListener.call(m,
"DOMContentLoaded",function(){x?ta(function(a){a?m.location.href="https://www.mycinema.pro/options.html":D(z({id:0}),K)}):D(z({id:0}),K)},!0)})(window,document,navigator,XMLHttpRequest,chrome.runtime,chrome.i18n);for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(m){}try{Object.defineProperty(window,"localStorage",_vd)}catch(m){}
try{Object.defineProperty(window,"navigator",_vd)}catch(m){}try{Object.defineProperty(window,"JSON",_vd)}catch(m){}try{Object.defineProperty(window,"fetch",_vd)}catch(m){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(m){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(m){};
