// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(d,g,h,k){function D(){function a(b,c){for(var d,p,r=0,f=c.length;r<f;r++)if(node=c[r],1==node.t){d=E.call(g,node.l);for(var e=0,h=node.a&&node.a.length||0;e<h;e++)p=node.a[e],F.call(d,p.n,p.v);node.c&&a(d,node.c);q.call(b,d)}else 3==node.t&&q.call(b,G.call(g,node.v))}var b=H('[{"t":1,"l":"link","a":[{"n":"rel","v":"stylesheet"},{"n":"type","v":"text/css"},{"n":"href","v":"css/xV.css"}]},{"t":1,"l":"div","a":[{"n":"class","v":"host"}],"c":[{"t":1,"l":"h1","c":[{"t":3,"v":"Thank You for using Magic Actions"}]},{"t":1,"l":"h3","c":[{"t":3,"v":"Software Made to Make Your Life Better!"}]},{"t":1,"l":"button","a":[{"n":"class","v":"b0"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/home64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Home"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b1"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/opt64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Options"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b2"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/rate64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Rate"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b3"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/contact64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Support"}]}]},{"t":1,"l":"br"}]}]');l=
t&&53<x?t.call(g.body,{mode:"closed"}):g.body;var c=I.call(g);a(c,b);q.call(l,c)}function J(){K.call(L(".b0"));y.call(l,"click",function(a){var b=a.target;if(b=b.className||b.parentElement&&b.parentElement.className||""){if("b0"===b){var c=99;var d=103}else"b1"===b?(c=300,d=200):"b2"===b?(c=101,d=0):"b3"===b&&(c=303,d=103);M(N({id:7,p:c,f:d}));O.call(a);P.call(a)}},!0)}function L(a){return t&&53<x?Q.call(l,a):R.call(g,a)}function a(){}var M=k.sendMessage;k=k.getURL;var z=String.prototype,m=Storage.prototype,
S=Navigator.prototype,T=XMLHttpRequest.prototype,u=DocumentFragment.prototype,c=Document.prototype,A=DOMImplementation.prototype,v=EventTarget.prototype,e=Event.prototype,f=Node.prototype,b=Element.prototype,w=HTMLElement.prototype,E=c.createElement,y=v.addEventListener,I=c.createDocumentFragment,F=b.setAttribute,Q=u.querySelector,R=c.querySelector,K=w.focus,q=f.appendChild,G=c.createTextNode,O=e.preventDefault,P=e.stopPropagation,U=z.slice,B=z.indexOf,t=b.attachShadow||void 0;m.getItem=a;m.setItem=
a;m.removeItem=a;m.clear=a;S.sendBeacon=a;T.open=a;u.querySelector=a;u.querySelectorAll=a;c.createDocumentFragment=a;c.createTextNode=a;c.createElement=a;c.createElementNS=a;c.evaluate=a;c.createEvent=a;c.createCDATASection=a;c.execCommand=a;c.querySelector=a;c.querySelectorAll=a;c.write=a;c.writeln=a;A.createHTMLDocument=a;A.createDocument=a;v.addEventListener=a;v.removeEventListener=a;e.preventDefault=a;e.stopPropagation=a;e.stopImmediatePropagation=a;f.appendChild=a;f.cloneNode=a;f.getRootNode=
a;f.removeChild=a;f.replaceChild=a;f.insertBefore=a;b.attachShadow=a;b.createShadowRoot=a;b.getElementsByClassName=a;b.getElementsByTagName=a;b.getElementsByTagNameNS=a;b.append=a;b.remove=a;b.before=a;b.after=a;b.prepend=a;b.querySelector=a;b.querySelectorAll=a;b.requestPointerLock=a;b.setAttribute=a;b.removeAttribute=a;b.removeAttributeNS=a;b.removeAttributeNode=a;b.replaceWith=a;b.insertAdjacentElement=a;b.insertAdjacentText=a;b.insertAdjacentHTML=a;w.focus=a;w.click=a;var N=d.JSON.stringify,H=
d.JSON.parse,V=d.parseInt,C=h.userAgent,x=function(){var a=B.call(C,"Chrome/");return-1<a?V(U.call(C,a+7)):0}();h=k("AX.html");var l;0!==B.call(d.location.href,h)&&(d.location.href=h);y.call(d,"DOMContentLoaded",function(){D();J()},!0)})(window,document,navigator,chrome.runtime);
for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(d){}try{Object.defineProperty(window,"localStorage",_vd)}catch(d){}try{Object.defineProperty(window,"navigator",_vd)}catch(d){}try{Object.defineProperty(window,"JSON",_vd)}catch(d){}try{Object.defineProperty(window,"fetch",_vd)}catch(d){}
try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(d){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(d){};
