// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(d,k,w,h){function E(a,f){var c=m.call(k,f.e);if(!c){(c=m.call(k,f.a))&&0<c.offsetHeight&&c.classList.add(f.b);var b=m.call(k,f.c);b&&(c=F.call(k,"iframe"),f.d?p.call(c,f.d,f.e):c.className=f.e,f.f&&(c.id=f.f),p.call(c,"scrolling","no"),p.call(c,"frameborder","0"),c.src=G(a),H.call(b,c))}}function I(){function a(a){var c=a?a:{w:640,h:350,vid:"pwHX9JT2APQ",lic:"YouTube License",t:"Magic Actions for YouTube™"};c.ver="7.3.0.4";c.ua=1;c.id=12;a=new w;J.call(a,"GET",c.rgba,!0);a.responseType=
"arraybuffer";a.onload=function(a){200==this.status&&(c.rgba=this.response,K(c,"https://www.mycinema.pro"))};L.call(a)}y||(y=!0,M.call(N,a),q(r({id:9}),a))}function O(a){for(var b=[],c=[3,0,0,-3],e,d=0,x=a.length;d<x;d++)e=c[d%4],d+e<x?z.call(b,A(a[d+e])):z.call(b,A(a[d]));return P.call(b,"")}function a(){}var G=h.getURL,N=h.onMessage,q=h.sendMessage,M=chrome.Event.prototype.addListener;h=Array.prototype;var l=Storage.prototype,Q=Navigator.prototype,t=w.prototype,B=DocumentFragment.prototype,e=Document.prototype,
C=DOMImplementation.prototype,u=EventTarget.prototype,v=Event.prototype,g=Node.prototype,b=Element.prototype,D=HTMLElement.prototype,m=e.querySelector,F=e.createElement,H=g.appendChild,p=b.setAttribute,R=u.addEventListener,J=t.open,L=t.send,z=h.push,P=h.join;l.getItem=a;l.setItem=a;l.removeItem=a;l.clear=a;Q.sendBeacon=a;t.open=a;B.querySelector=a;B.querySelectorAll=a;e.createDocumentFragment=a;e.createTextNode=a;e.createElement=a;e.createElementNS=a;e.evaluate=a;e.createEvent=a;e.createCDATASection=
a;e.execCommand=a;e.querySelector=a;e.querySelectorAll=a;e.write=a;e.writeln=a;C.createHTMLDocument=a;C.createDocument=a;u.addEventListener=a;u.removeEventListener=a;v.preventDefault=a;v.stopPropagation=a;v.stopImmediatePropagation=a;g.appendChild=a;g.cloneNode=a;g.getRootNode=a;g.removeChild=a;g.replaceChild=a;g.insertBefore=a;b.attachShadow=a;b.createShadowRoot=a;b.getElementsByClassName=a;b.getElementsByTagName=a;b.getElementsByTagNameNS=a;b.append=a;b.remove=a;b.before=a;b.after=a;b.prepend=a;
b.querySelector=a;b.querySelectorAll=a;b.requestPointerLock=a;b.setAttribute=a;b.removeAttribute=a;b.removeAttributeNS=a;b.removeAttributeNode=a;b.replaceWith=a;b.insertAdjacentElement=a;b.insertAdjacentText=a;b.insertAdjacentHTML=a;D.focus=a;D.click=a;var r=d.JSON.stringify,S=d.JSON.parse,A=String.fromCharCode,T=Date.now,K=d.postMessage,y;R.call(d,"message",function(a){if("https://www.mycinema.pro"===(a.origin||"")&&a.data.constructor===Array){try{var b=S(O(a.data))}catch(c){b={}}b.t&&(a=T()-b.t,
1E3>a&&(a=b.i,2==a?q(r({id:2,url:b.u,incognito:b.p})):300==a?E("Mj.html",b):303==a?I():304==a&&q(r({id:0}),function(a){a=a.opt;b.ui&&a.a0&&a.a4&&a.ui&&k.documentElement.classList.add(b.ui)})))}},!0)})(window,document,XMLHttpRequest,chrome.runtime);for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(d){}
try{Object.defineProperty(window,"localStorage",_vd)}catch(d){}try{Object.defineProperty(window,"navigator",_vd)}catch(d){}try{Object.defineProperty(window,"JSON",_vd)}catch(d){}try{Object.defineProperty(window,"fetch",_vd)}catch(d){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(d){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(d){};
