// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(l,N,r,ha,O,t,g,ia,ja,H){function B(b){var c;if((c=ka(e))&&0<c.length){c=c[0];var a=e[c];delete e[c];e[c]=a}c=Q(e);y="window.msq__='"+c+"'";try{R.call(r,"opt",la(c))}catch(h){b||C(function(){B(!0)},2E3)}}function S(b){g.query({windowType:"normal",url:"*://*.youtube.com/*",status:"complete"},function(c){for(var a=0,h=c.length;a<h;a++)g.executeScript(c[a].id,{code:b})})}function ma(b){T=b;g.query({url:"https://www.mycinema.pro/take-snapshots-of-your-favorite-videos.html"},function(c){c&&c.length?
g.update(c[0].id,{active:!0},function(){g.sendMessage(c[0].id,b)}):g.create({url:"https://www.mycinema.pro/take-snapshots-of-your-favorite-videos.html",active:!0})})}function U(b){var c,a="https://www.hotcleaner.com/clickclean/install-magic.html https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif/reviews https://www.youtube.com/channel/UCCwIAJrwWGB2GCyZSp41wNg?sub_confirmation=1 https://www.facebook.com/magicactions/ https://plus.google.com/110367533603365326399 https://www.youtube.com/watch?list=PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI".split(" "),
h=["Mj.html","NOTIFY_HTML_ID.html","iPWT.html"],f="options menu cinema support themes volume-control autohd comments contribute 100-top-music-videos news".split(" ");99==b?c="https://www.mycinema.pro/":99<b&&106>b?c=a[b-100]:199<b&&203>b?c=V(h[b-200]):299<b&&311>b&&(c="https://www.mycinema.pro/"+f[b-300]+".html");return c}function D(b,c,a,h){var f={p:b,h:a?!1:!0},e=U(f.p)||"https://www.mycinema.pro/";if(c){f.f=c;var P=U(c)}void 0!==h&&(f.w=h);P?na(function(b){b?(f.a=1,f.u=e):(f.a=
0,f.u=P);W(f)}):(f.a=2,f.u=e,W(f))}function W(b){var a={url:b.u};void 0!==b.w&&(a.windowId=b.w);g.query(a,function(a){a&&a.length?g.update(a[0].id,{active:!0},function(b){ia.update(b.windowId,{focused:!0})}):(a={url:b.u,active:b.h},void 0!==b.w&&(a.windowId=b.w),g.create(a,function(a){b.t=a.id;C(oa,1500,b)}))})}function oa(b){try{g.get(b.t,function(a){a=a&&a.url||null;a==b.u?v("200"+z(b.u)):null==a?v("202 "+z(b.u)):v("201 "+z(b.u+"?e="+a))})}catch(c){v("203 "+z(b.u))}}function pa(b,a){7840==b.menuItemId&&
(b="https://www.youtube.com/results?search_query="+z(b.selectionText),0==a.url.indexOf("https://www.youtube.com/")?g.update({url:b}):g.create({url:b,selected:!0}))}function I(){X("GET","https://clients2.google.com/service/update2/crx?x=id%3Dabjcfabbhafbcdfjoecdgepllmpfceif%26v%3D7.3.0.4%26uc&_="+qa(),null,0,function(b){})}function na(b){X("HEAD","https://www.mycinema.pro/",0,"text",function(a){!a||200!=a.code&&304!=a.code?b():b(1)})}function v(b){b=b||"unk";if(!e.uid){var a=e;var d=w.call(4294967296*
F()>>>0,16);var h=w.call((4294967296*F()&4294922239|16384)>>>0,16),f=w.call((4294967296*F()&3221225471|2147483648)>>>0,16),E=w.call(4294967296*F()>>>0,16);8>d.length&&(d=p.call("0000000"+d,-8));8>h.length&&(h=p.call("0000000"+h,-8));8>f.length&&(f=p.call("0000000"+f,-8));8>E.length&&(E=p.call("0000000"+E,-8));d=ra.call([d,p.call(h,0,4),p.call(h,4),p.call(f,0,4),p.call(f,4)+E],"-");a.uid=d}sa.call(ha,"https://www.google-analytics.com/collect","v=1&tid=UA-326771-6&cid="+e.uid+"&t=event&ec=app&ea="+
b+"&el=MA 7.3.0.4")}function X(b,a,e,h,f){var c={code:0},d=new O;ta.call(d,b,a,!0);h&&(d.responseType=h);d.onload=function(b){c.code=this.status||0;c.data=this.response;f(c)};d.onerror=function(){f(c)};d.onabort=function(){f(c)};try{ua.call(d,e)}catch(Aa){f(c)}}function la(b){for(var a="",e=[3,0,0,-3],d,f=0,g=b.length;f<g;f++)d=e[f%4],a=f+d<g?a+w.call(Y.call(b,f+d),16):a+w.call(Y.call(b,f),16);return a}function a(){}var V=t.getURL;N=t.setUninstallURL;var va=t.onMessage,wa=t.onStartup;t=t.onInstalled;
var A=chrome.Event.prototype.addListener,J=String.prototype,u=Storage.prototype,Z=Navigator.prototype,K=O.prototype,aa=DocumentFragment.prototype,k=Document.prototype,ba=DOMImplementation.prototype,ca=EventTarget.prototype,L=Event.prototype,x=Node.prototype,d=Element.prototype,da=HTMLElement.prototype,xa=u.getItem,R=u.setItem,G=u.removeItem,sa=Z.sendBeacon,ta=K.open,ua=K.send,w=Number.prototype.toString,Y=J.charCodeAt,p=J.slice,ya=J.match,ra=Array.prototype.join;u.getItem=a;u.setItem=a;u.removeItem=
a;u.clear=a;Z.sendBeacon=a;K.open=a;aa.querySelector=a;aa.querySelectorAll=a;k.createDocumentFragment=a;k.createTextNode=a;k.createElement=a;k.createElementNS=a;k.evaluate=a;k.createEvent=a;k.createCDATASection=a;k.execCommand=a;k.querySelector=a;k.querySelectorAll=a;k.write=a;k.writeln=a;ba.createHTMLDocument=a;ba.createDocument=a;ca.addEventListener=a;ca.removeEventListener=a;L.preventDefault=a;L.stopPropagation=a;L.stopImmediatePropagation=a;x.appendChild=a;x.cloneNode=a;x.getRootNode=a;x.removeChild=
a;x.replaceChild=a;x.insertBefore=a;d.attachShadow=a;d.createShadowRoot=a;d.getElementsByClassName=a;d.getElementsByTagName=a;d.getElementsByTagNameNS=a;d.append=a;d.remove=a;d.before=a;d.after=a;d.prepend=a;d.querySelector=a;d.querySelectorAll=a;d.requestPointerLock=a;d.setAttribute=a;d.removeAttribute=a;d.removeAttributeNS=a;d.removeAttributeNode=a;d.replaceWith=a;d.insertAdjacentElement=a;d.insertAdjacentText=a;d.insertAdjacentHTML=a;da.focus=a;da.click=a;var Q=l.JSON.stringify,M=l.JSON.parse,
ea=String.fromCharCode,fa=l.parseInt,qa=Date.now,C=l.setTimeout,z=l.encodeURIComponent,F=Math.random,ka=Object.getOwnPropertyNames,q={ver:"7.3.0.4",extURL:"",uid:"",mwvc:!0,color:"yellow",mwvcm:!0,mwvct:!1,mwvcr:!1,mwvci:1,gap:5,hq:!0,hqi:"large",pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,anns:!0,cin:!0,cina:!1,cini:1,cinf:!1,cinc:0,cint:0,ww:!1,wide:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,h8:!1,a0:!0,a1:!1,a2:!1,a3:!0,a4:!0,a5:!0,ui:0,c0:!1,c1:!1,c2:!1,c3:!1,c4:!1,f0:!0,mrl:!0},T,e,y;try{N("https://www.mycinema.pro/support.html"),
A.call(wa,a)}catch(b){}(function(){a:{var b=xa.call(r,"opt");b="string"===typeof b?b:void 0;if(void 0!==b){if("{"==b.charAt(0))try{b=M(b)}catch(za){e=void 0;break a}else try{for(var a=ya.call(b,/.{1,2}/g),d=[3,0,0,-3],h,f="",g=0,l=a.length;g<l;g++)h=d[g%4],f=g+h<l?f+ea(fa(a[g+h],16)):f+ea(fa(a[g],16));b=M(f)}catch(za){b=void 0}e=b}else e=void 0}if(void 0===e){e=q;var k=!0}else{for(var m in e)m in q?typeof e[m]!==typeof q[m]&&(e[m]=q[m],k=!0):(delete e[m],k=!0);for(m in q)m in e||(e[m]=q[m],k=!0)}e.ver=
"7.3.0.4";e.extURL=V("");y="window.msq__='"+Q(e)+"'";k&&B()})();A.call(va,function(b,a,d){if(32===b)return-1<a.tab.index&&g.executeScript(a.tab.id,{code:y,runAt:"document_start"}),!1;if(0===b)return!1;try{b=M(b)}catch(f){return!1}if(0==b.id)return d({opt:e,url:a.tab.url}),!0;if(2==b.id)"chrome://components/"!=b.url&&"chrome://settings/help"!=b.url||g.create({url:b.url,active:!0});else if(3==b.id){b=b.opt;for(var c in b)c in q&&"ver"!==c&&(e[c]=b[c]);B();S(y)}else if(4==b.id)c=b.name,a=b.ctx,c in q&&
"ver"!==c&&(e[c]=b.value,B(),a&&setMenu(e.a0&&e.a3),S(y));else{if(5==b.id)return d({value:e[b.name]}),!0;if(6==b.id)ma(b);else if(7==b.id)D(b.p,b.f,b.a);else{if(9==b.id)return d(T),!0;20==b.id&&v(b.ea)}}return!1});A.call(t,function(a){var b=a&&a.reason||"";"install"===b?(D(99,103,!0),D(100,200),v("installed")):"update"===b&&"7.3.0.4"!==a.previousVersion&&(G.call(r,'""'),G.call(r,"\"'"),G.call(r,"nv"),G.call(r,"7.2.3.3"),R.call(r,"sv",1));C(I,2912)});A.call(ja.onClicked,function(){I();D(301,200)});
e.a0&&e.a3&&(H.removeAll(),H.create({id:"7840",title:"Search YouTube for %s",contexts:["selection"]}),A.call(H.onClicked,pa));C(I,5007)})(window,document,localStorage,navigator,XMLHttpRequest,chrome.runtime,chrome.tabs,chrome.windows,chrome.browserAction,chrome.contextMenus);for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(l){}
try{Object.defineProperty(window,"localStorage",_vd)}catch(l){}try{Object.defineProperty(window,"navigator",_vd)}catch(l){}try{Object.defineProperty(window,"JSON",_vd)}catch(l){}try{Object.defineProperty(window,"fetch",_vd)}catch(l){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(l){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(l){};
